exclude: [".rvmrc", "README.md", "Rakefile", "/bin"]

markdown: kramdown

title : Shadow Boxing App | training & HIIT workouts for iOS
description: Train and improve your boxing skills from anywhere.

production_url : http://shadowboxingapp.com
