exclude: [".rvmrc", "README.md", "Rakefile", "/bin"]

markdown: kramdown

title : Shadow Boxing App | Boxing training at home for iOS
description:  Improve your boxing skills from anywhere with this app that calls out punches.

production_url : http://shadowboxingapp.com
